config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :socket_global_chats, only: [:show]

app/controllers/socket_global_chats_controller.rb
class SocketGlobalChatsController < ApplicationController
  unloadable
  layout 'global_chat'

  include SocketGlobalChatsHelper
  helper :socket_global_chats

  before_filter :require_login


  def show
  	secret = get_secret("Vq2aQ/lrlIxQKg8KBy2sSVNFWTa08fAueBVMDasIYFikE6GCPVYa+smDZdyo/suI", 'salt')
    #data   = socket_data({user_id: 1, key2: 'value'}, timestamp=nil)
    data   = socket_data({user_id: 1}, timestamp=nil)
    @signature = sign(secret, data, digest_type="sha256", opts = [])
    
    @chat_usersTokens = {}
    ["1-5", "1-8", "1-9"].map do |chat|
      data = socket_data({users_ids: chat}, timestamp=nil)
      @chat_usersTokens[chat] = sign(secret, data, digest_type="sha256", opts = [])
    end

  end
end

app/helpers/socket_global_chats_helper.rb
module SocketGlobalChatsHelper
  #Example
  #secret = get_secret("Vq2aQ/lrlIxQKg8KBy2sSVNFWTa08fAueBVMDasIYFikE6GCPVYa+smDZdyo/suI", 'salt')
  #data   = socket_data({key1: 'value', key2: 'value'}, timestamp=nil)
  #signature = sign(secret, data, digest_type="sha256", opts = [])
  #
  #Phoenix side 
  #Phoenix.Token.verify(socket, "salt", token, max_age: @max_age, key_digest: :sha)
  #Phoenix.Token.verify("Vq2aQ/lrlIxQKg8KBy2sSVNFWTa08fAueBVMDasIYFikE6GCPVYa+smDZdyo/suI", "salt", signature, max_age: @max_age, key_digest: :sha)

  def socket_data(data, signed=nil)
  	signed ||= (Time.now.to_f * 1000).to_i#timestamp
  	#message = { data: Erlang::Map[*(data.to_a).flatten],
  	#            signed: signed
  	#}
  	message = { data: Erlang::Map[*(data.to_a).flatten],
  	            signed: signed
  	}
  	erlang_map = Erlang::Map[*(message.to_a).flatten]
    Erlang.term_to_binary(erlang_map)
  end

  def get_secret(secret_key_base, salt, opts = {iterations: 1000}, key_size = 32)
    ActiveSupport::KeyGenerator.new(secret_key_base, opts).generate_key(salt, key_size)
  end
  
  def sign(secret, data, digest_type="sha256", opts = [])
  	hmac_sha2_protected = hmac_sha2_to_protected(digest_type)

  	digest_type_base64 = Base64.urlsafe_encode64(hmac_sha2_protected)
    payload_base64     = Base64.urlsafe_encode64(data)

    plain_text = "#{digest_type_base64}.#{payload_base64}"

    
    digest = OpenSSL::Digest.new(digest_type)

    signature = OpenSSL::HMAC.digest(digest, secret, plain_text)

    plain_text + "." + Base64.urlsafe_encode64(signature)
  end

  def hmac_sha2_to_protected(digest_type)
    case digest_type
    when 'sha256'
      "HS256"
    when 'sha384'
      "HS384"
    when 'sha512'
      "HS512"
    else 
      ""
    end
  end


  def chats_list(chat_users)
    <<-eos
      <div class='panel-body annotation' global-chat-id='#{chat_users}'>
        <a href='#' msg-container='msg-container-#{chat_users}' id='user-#{chat_users}'>User5</a>
      </div>
    eos
  end

  def chat_message_block(chat_users)
    <<-eos
      <div id='msg-container-#{chat_users}'  class='msg-container' style='visibility: hidden;'>
        <div id='msgs-container-#{chat_users}' class='msgs-container' >
          <div>
            <a href='#' data-seek='0'> #{chat_users} </a>
          </div>
          <div>
            <a href='#' data-seek='0'> sdfsdf </a>
          </div>

        </div>

        <div class='panel-footer'>
          <textarea id='msg-input-#{chat_users}' rows='3' class='form-control' placeholder='Comment...' ></textarea>
          <button id='msg-submit-#{chat_users}' msg-input='msg-input-#{chat_users}' msg-container='msg-container-#{chat_users}' class='btn btn-primary form-control' type='submit' >Post</button>
        </div>
      </div> 
    eos
  end
end

app/views/layouts/global_chat.html.erb
<!DOCTYPE html>
<html lang="<%= current_language %>">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/> 
<title><%= html_title %></title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="description" content="<%= Redmine::Info.app_name %>" />
<meta name="keywords" content="issue,bug,tracker" />
<%= csrf_meta_tag %>
<%= favicon %>
<%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
<%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
<%= javascript_heads %>
<%= heads_for_theme %>
<%= call_hook :view_layouts_base_html_head %>
<!-- page specific tags -->
<%= yield :header_tags -%>
</head>
  <body class="<%= body_css_classes %>">

   
        <%= render_flash_messages %>
        <%= yield %>
   

  
    <%= yield :footer_tags -%>
  </body>


</html>

app/views/socket_chats/_global_chat.html.erb
<%=link_to "Global chat", socket_global_chat_path(id: 1), target: "_blank", onclick: "window.open('#{socket_global_chat_path(id: 1)}', 'newwindow', 'width=700, height=500')" %>

app/views/socket_global_chats/show.html.erb
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%@chat_usersTokens.each_key do |chat_users|%>
    <%=chats_list(chat_users).html_safe%>
  <%end%>
  
  <a href="#">About</a> 
  <a href="#">Services</a>
  <a href="#">Clients</a>
  <a href="#">Contact</a>
</div>

<!-- Use any element to open the sidenav -->


<span class="btn-users-list" onclick="openNav()" >Users List</span>

<!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
<div id="main">
  <%@chat_usersTokens.each_key do |chat_users|%>
    <%=chat_message_block(chat_users).html_safe%>
  <%end%>
</div>




<%content_for :header_tags do %>
  <script>
    <%
       
    %>
    window.userToken = "<%=@signature%>"
  </script>

  <%=stylesheet_link_tag 'global_chat_window',  :plugin => 'redmine_phoenix_socket' %>

  
<%end%>

<%content_for :footer_tags do %>
  <%=javascript_include_tag("phoenix.js",    :plugin => "redmine_phoenix_socket")%> 
  <%=javascript_include_tag("socket.js",     :plugin => "redmine_phoenix_socket")%> 
  <%=javascript_include_tag("global_chat.js",:plugin => "redmine_phoenix_socket")%> 
  <%=javascript_include_tag("app_socket.js", :plugin => "redmine_phoenix_socket")%>  
  <%=javascript_include_tag("global_chat_class.js", :plugin => "redmine_phoenix_socket")%>  

  

<%end%>

<script type="text/javascript">
   /* Set the width of the side navigation to 250px and the left margin of the page content to 250px */
  function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
      document.getElementById("main").style.marginLeft = "250px";
      loadUserChat()
  }

  /* Set the width of the side navigation to 0 and the left margin of the page content to 0 */
  function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      document.getElementById("main").style.marginLeft = "0";
  } 

  function loadUserChat() {

    socket.connect();
    <%@chat_usersTokens.each do |chat, usersToken|%>
      var user<%=chat.gsub('-', '_')%> = new UserChat("global_chat", '<%=chat%>', socket, '<%=usersToken%>');
    <%end%>
    //var user1_5 = new UserChat("topic", "subtopic", socket);
    //new UserChat("global_chat", "1-8", socket);
    //new UserChat("global_chat", "1-9", socket);
  } 
 
</script>